(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const native = !!window.Capacitor?.isNativePlatform?.();
  const demo = new URLSearchParams(location.search).has('demo');
  let address = localStorage.getItem('g1.address') || (native ? 'http://10.42.0.1:8787' : location.origin);
  let library = [], motions = [], selected = null, editing = null, pendingMotion = null, pendingUniStore = null, danceFilter = 'all', motionFilter = 'all', utilityFilter = 'all', connected = false, busy = false, polling = false, robotBusy = false;
  let status = {state:'idle', routine_id:null, robot_connected:false}, audioOutput='browser', browserAudio=null, browserAudioOnly=false, browserAudioDanceId=null, musicOnlyPlayback=false, toastTimer;
  const events = [];
  let unistore = {apps:[],cached:false,error:null}, bluetoothDevices=[], bluetoothSearch=[], featured=[], featuredIndex=-1;
  const unistoreFavoritesKey='g1.unistore-favorites';
  const libraryFavoritesKey='g1.library-favorites';
  function readUniStoreFavorites(){try{const value=JSON.parse(localStorage.getItem(unistoreFavoritesKey)||'[]');return new Set(Array.isArray(value)?value.filter(id=>typeof id==='string'):[]);}catch{return new Set();}}
  function syncPreferences(){if(demo)return Promise.resolve();return request('/api/app-data/preferences','PUT',JSON.stringify({library_favorites:[...readLibraryFavorites()],unistore_favorites:[...readUniStoreFavorites()]}),{'Content-Type':'application/json'}).catch(()=>{});}
  function saveUniStoreFavorites(favorites){localStorage.setItem(unistoreFavoritesKey,JSON.stringify([...favorites]));syncPreferences();}
  function readLibraryFavorites(){try{const value=JSON.parse(localStorage.getItem(libraryFavoritesKey)||'[]');return new Set(Array.isArray(value)?value.filter(id=>typeof id==='string'):[]);}catch{return new Set();}}
  function saveLibraryFavorites(favorites){localStorage.setItem(libraryFavoritesKey,JSON.stringify([...favorites]));syncPreferences();}
  function applyPreferences(value){if(!value||typeof value!=='object')return;if(Array.isArray(value.library_favorites))localStorage.setItem(libraryFavoritesKey,JSON.stringify(value.library_favorites));if(Array.isArray(value.unistore_favorites))localStorage.setItem(unistoreFavoritesKey,JSON.stringify(value.unistore_favorites));}
  async function refreshUniStore(){
    if(demo){unistore={apps:[],cached:false,error:null};renderCards();return;}
    try{unistore=await request('/api/unistore');}catch(e){unistore={...unistore,cached:true,error:'UniStore discovery unavailable.'};}
    renderCards();
  }
  const demoLibrary = ['Midnight motion','Electric soul','After hours','Golden groove','Neon steps','Slow orbit'].map((name,i) => ({id:'session-'+i,name:['Popping','Welcome','Recovery stand','Thinking','Neon Shuffle','Slow Orbit'][i],song_title:name,audio:i<4?null:i===5?null:'track.mp3',artwork_url:null,kind:i<4?'mimic':'routine',category:i<4?['dance','greeting','recovery','gesture'][i]:'dance',duration:i<4?10+i:undefined}));
  const demoMotions = [
    ['high-wave','Wave','👋'],['shake-hand','Shake hand','🤝'],['high-five','High five','✋'],['clap','Clap','👏'],
    ['hug','Hug','🫂'],['heart','Heart','🫶'],['right-heart','Right heart','♡'],['face-wave','Face wave','🙋'],
    ['hands-up','Hands up','🙌'],['right-hand-up','Right hand up','☝'],['reject','Reject','🙅'],['x-ray','X-ray','🩻'],
    ['left-kiss','Left kiss','💋'],['right-kiss','Right kiss','💋'],['two-hand-kiss','Two-hand kiss','😘'],['release-arm','Release arms','↔']
  ].map(([id,name,icon])=>({id,name,icon}));
  function log(text) { events.unshift(new Date().toLocaleTimeString()+'  '+text); $('logs').textContent = events.slice(0,80).join('\n'); }
  function toast(text) { if(/error|could not|failed|invalid|choose |interrupted|unavailable|no playing|no mp3|enter |stop playback|another routine|rejected|not found/i.test(text)){errorToast(text);return;}clearTimeout(toastTimer);$('toast').hidden=true;log(text); }
  function errorToast(text) { const notice=$('toast');notice.textContent=text;notice.classList.add('error');notice.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>notice.hidden=true,5000);log(text); }
  function connection(serviceOk, robotOk=status.robot_connected===true) {
    connected=serviceOk;
    status.robot_connected=serviceOk&&robotOk;
    const state=robotBusy?'connecting':status.robot_connected?'online':'offline';
    document.querySelectorAll('[data-robot-status]').forEach(label=>{label.textContent=robotBusy?'● Connecting…':status.robot_connected?'● Robot online':'● Robot offline';label.className='status-'+state;});
    document.querySelectorAll('[data-connect-robot]').forEach(button=>{button.textContent=status.robot_connected?'Connected':'Connect robot';button.disabled=robotBusy||status.robot_connected;});
    $('robot-walk-run').disabled=robotBusy||!status.robot_connected||busy;
    $('robot-ready-mode').disabled=robotBusy||!status.robot_connected||busy;
    $('robot-damped-mode').disabled=robotBusy||!status.robot_connected;
    renderPlayer();
    renderCards();
  }
  function fallback(r) { const hue = [...r.id].reduce((n,c)=>n+c.charCodeAt(0),0)*29%360; const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="hsl(${hue},60%,36%)"/><stop offset="1" stop-color="hsl(${(hue+65)%360},70%,12%)"/></linearGradient></defs><path d="M0 0h600v600H0z" fill="url(#g)"/><g fill="none" stroke="hsl(${(hue+30)%360},90%,76%)" stroke-width="26" opacity=".85"><ellipse cx="300" cy="300" rx="210" ry="85" transform="rotate(-30 300 300)"/><ellipse cx="300" cy="300" rx="210" ry="85" transform="rotate(30 300 300)"/><ellipse cx="300" cy="300" rx="210" ry="85" transform="rotate(90 300 300)"/></g><circle cx="300" cy="300" r="30" fill="#efffea"/></svg>`;return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg); }
  function art(r){if(!r)return'assets/app_icon.png';if(r.artwork_url)return address+r.artwork_url;if(r.cover||r.icon_url)return r.cover||r.icon_url;return fallback(r);}
  function browserAudioUrl(item){return item.kind==='routine'?'/api/routines/'+encodeURIComponent(item.id)+'/audio-file':'/api/media/'+encodeURIComponent(item.kind)+'/'+encodeURIComponent(item.id)+'/audio-file';}
  function stopBrowserAudio(){if(browserAudio){browserAudio.pause();browserAudio.currentTime=0;browserAudio=null;}browserAudioOnly=false;browserAudioDanceId=null;musicOnlyPlayback=false;}
  function playBrowserAudio(item, linkedToDance=false){if(!item?.audio)return;stopBrowserAudio();browserAudioOnly=!linkedToDance;browserAudioDanceId=linkedToDance?item.id:null;musicOnlyPlayback=!linkedToDance;const audio=new Audio(address+browserAudioUrl(item));browserAudio=audio;audio.onerror=()=>{if(browserAudio===audio){browserAudio=null;browserAudioDanceId=null;musicOnlyPlayback=false;toast('Browser audio could not load. Check this device’s media volume and that the MP3 is attached.');renderPlayer();}};audio.onended=()=>{if(browserAudio===audio){browserAudio=null;browserAudioDanceId=null;musicOnlyPlayback=false;if(status.routine_id===item.id){status={...status,state:'complete'};renderPlayer();}}};audio.play().catch(error=>toast('Browser audio could not start: '+error.message));}
  function renderFeatured(){const item=featured[featuredIndex],active=status.state==='playing'||status.state==='paused';$('featured-previous').disabled=featured.length<2;$('featured-next').disabled=featured.length<2;$('featured-position').textContent=featured.length?(featuredIndex+1)+' / '+featured.length:'0 / 0';$('featured-play').disabled=!item||!connected||(!demo&&!status.robot_connected)||busy||active;$('featured-music').disabled=!item?.audio||!connected||busy||active;if(!item){$('featured-title').textContent='Star a dance to feature it here.';$('featured-subtitle').textContent='Your starred dances will appear here at random.';$('featured-art').src='assets/app_icon.png';return;}$('featured-title').textContent=item.song_title||item.name;$('featured-subtitle').textContent=item.kind==='unistore'?'UniStore '+(item.category==='martial-art'?'Martial Arts':'Dance'):'Robot-installed dance';$('featured-art').src=art(item);$('featured-art').alt='Featured dance: '+item.name;}
  function setFeatured(items){const prior=featured[featuredIndex],priorKey=prior&&prior.kind+':'+prior.id;featured=items;let index=featured.findIndex(item=>item.kind+':'+item.id===priorKey);if(index<0)index=featured.length?Math.floor(Math.random()*featured.length):-1;featuredIndex=index;renderFeatured();}
  function moveFeatured(direction){if(featured.length<2)return;featuredIndex=(featuredIndex+direction+featured.length)%featured.length;renderFeatured();}
  function createCover(item, source){const cover=document.createElement('div');cover.className='cover';const img=document.createElement('img');img.src=source||art(item);img.alt='Cover for '+(item.song_title||item.name);img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>{img.onerror=null;img.src=fallback(item);};cover.append(img);if(item.video_url){const video=document.createElement('video');video.className='tile-preview';video.src=address+item.video_url;video.muted=true;video.loop=true;video.playsInline=true;video.preload='metadata';cover.append(video);cover.onmouseenter=()=>video.play().catch(()=>{});cover.onmouseleave=()=>{video.pause();video.currentTime=0;};}return cover;}
  async function request(path, method='GET', body, headers={}, timeout=12000) {
    const controller=new AbortController(), timer=setTimeout(()=>controller.abort(),timeout);
    try { const response=await fetch(address+path,{method,body,headers,signal:controller.signal}); const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;} finally {clearTimeout(timer);}
  }
  function renderCards(){
    const search=$('search').value.toLowerCase(),isUtility=r=>['recovery','utility'].includes(r.category),mimics=library.filter(r=>r.kind==='mimic'&&!isUtility(r)),unistoreActions=unistore.apps.map(a=>({...a,kind:'unistore',category:(a.category||[]).some(c=>String(c).toLowerCase().includes('martial'))?'martial-art':'dance'})),dances=[...mimics,...unistoreActions],utilities=library.filter(r=>r.kind==='mimic'&&isUtility(r)),localRoutines=library.filter(r=>r.kind!=='mimic');
    const presets=motions.map(m=>({...m,kind:'preset',category:'preset',artwork_url:null})),otherMotions=[...localRoutines,...presets];
    $('cards').replaceChildren();$('motion-library-cards').replaceChildren();$('count').textContent=dances.length;$('motion-library-count').textContent=otherMotions.length;
    $('utility-library-cards').replaceChildren();$('utility-library-count').textContent=utilities.length;
    const searched=r=>(r.name+' '+(r.song_title||'')).toLowerCase().includes(search);
    const favorites=readLibraryFavorites(),unistoreFavorites=readUniStoreFavorites(),favoriteKey=r=>r.kind+':'+r.id,isFavorite=r=>r.kind==='unistore'?unistoreFavorites.has(r.id):favorites.has(favoriteKey(r)),sortFavorites=items=>items.sort((a,b)=>Number(isFavorite(b))-Number(isFavorite(a))||((a.song_title||a.name).localeCompare(b.song_title||b.name)));
    setFeatured(dances.filter(isFavorite));
    const visibleDances=sortFavorites(dances.filter(r=>searched(r)&&(danceFilter==='all'||(danceFilter==='music'?!!r.audio:r.category===danceFilter))));
    const visibleMotions=sortFavorites(otherMotions.filter(r=>searched(r)&&(motionFilter==='all'||r.kind===motionFilter)));
    const visibleUtilities=sortFavorites(utilities.filter(r=>searched(r)&&(utilityFilter==='all'||r.category===utilityFilter)));
    const append=(container,r)=>{const preset=r.kind==='preset',isUniStore=r.kind==='unistore',tile=document.createElement('div'),key=favoriteKey(r),favorited=isFavorite(r);tile.className='tile'+(selected?.kind===r.kind&&selected?.id===r.id?' selected':'');
      const primary=document.createElement('button');primary.type='button';primary.className='tile-main';primary.setAttribute('aria-label','Select '+(r.song_title||r.name));primary.setAttribute('aria-pressed',selected?.kind===r.kind&&selected?.id===r.id?'true':'false');
      const cover=createCover(r);if(preset){const icon=document.createElement('span');icon.className='preset-cover-icon';icon.textContent=r.icon;icon.setAttribute('aria-hidden','true');cover.append(icon);}
      const title=document.createElement('strong');title.textContent=r.song_title||r.name;const sub=document.createElement('small');sub.textContent=isUniStore?'UniStore · '+(r.category==='martial-art'?'Martial Arts':'Dance')+(r.audio?' · MP3 attached':' · No music'):r.kind==='mimic'?'Robot mimic · '+Math.round(r.duration)+' sec'+(r.audio?' · MP3 attached':''):preset?'Preset arm action'+(r.audio?' · MP3 attached':''):r.audio?r.name+' · MP3 attached':'Local routine · No music';primary.append(cover,title,sub);primary.onclick=()=>{selected=r;renderCards();renderPlayer();};
      const favorite=document.createElement('button');favorite.type='button';favorite.className='library-favorite'+(favorited?' selected':'');favorite.textContent=favorited?'★':'☆';favorite.setAttribute('aria-label',(favorited?'Remove ':'Add ')+(r.song_title||r.name)+(favorited?' from':' to')+' favorites');favorite.setAttribute('aria-pressed',String(favorited));favorite.title=favorited?'Remove from favorites':'Add to favorites';favorite.onclick=()=>{if(isUniStore){const next=readUniStoreFavorites();if(next.has(r.id))next.delete(r.id);else next.add(r.id);saveUniStoreFavorites(next);}else{const next=readLibraryFavorites();if(next.has(key))next.delete(key);else next.add(key);saveLibraryFavorites(next);}renderCards();};
      const play=document.createElement('button');play.type='button';play.className='tile-action';play.textContent='▶';play.setAttribute('aria-label','Start '+r.name);play.title='Start action';play.disabled=!connected||(!demo&&!status.robot_connected)||busy||status.state==='playing'||status.state==='paused';play.onclick=()=>startSelected(r);tile.append(primary,favorite);if(!isUniStore)tile.append(play);container.append(tile);
    };
    visibleDances.forEach(r=>append($('cards'),r));visibleMotions.forEach(r=>append($('motion-library-cards'),r));
    visibleUtilities.forEach(r=>append($('utility-library-cards'),r));$('utility-library-empty').hidden=visibleUtilities.length>0;
    $('empty').hidden=visibleDances.length>0;$('motion-library-empty').hidden=visibleMotions.length>0;
    $('empty').querySelector('h3').textContent=dances.length?'No dances match this view.':'No dances found.';
  }
  function renderPlayer(){const active=status.state==='playing'||status.state==='paused',anyPlayback=active||!!browserAudio,musicOnlyActive=musicOnlyPlayback,mimicActive=active&&status.motion_id?.startsWith('mimic-');const current=library.find(r=>r.id===status.routine_id);const shown=active&&current?current:selected;
    $('now-art').src=art(shown);$('now-title').textContent=shown?.song_title||shown?.name||'Choose your next track';$('now-subtitle').textContent=shown?shown.name:'Select a tile to get started';
    $('toggle').textContent=status.state==='playing'&&!musicOnlyActive?'Ⅱ':'🕺';$('toggle').setAttribute('aria-label',status.state==='playing'&&!musicOnlyActive?'Pause dance':status.state==='paused'?'Resume dance':'Start dance');
    $('toggle').disabled=!connected||(!demo&&!status.robot_connected)||busy||mimicActive||musicOnlyActive||(!active&&!selected);$('stop').disabled=!connected||(!anyPlayback&&status.state!=='error');$('music').disabled=!connected||busy||anyPlayback||!selected?.audio;$('edit').disabled=!selected||busy;
  }
  async function refresh(){try{if(demo){library=demoLibrary;motions=demoMotions;status={...status,robot_connected:false};}else{const [result,motionResult,latest,settings,preferences]=await Promise.all([request('/api/routines'),request('/api/motions').catch(()=>({motions:[]})),request('/api/status'),request('/api/settings'),request('/api/app-data/preferences').catch(()=>null)]);library=result.routines;motions=motionResult.motions;status=latest;audioOutput=settings.audio_output;setAudioOutput(audioOutput);applyPreferences(preferences);}if(selected?.kind!=='unistore'&&selected)selected=library.find(r=>r.id===selected.id)||motions.find(m=>m.id===selected.id)||null;connection(true,status.robot_connected);renderCards();renderPlayer();log('Library refreshed: '+library.length+' items');}catch(e){connection(false,false);toast('Could not connect. Join the G1 hotspot and check Settings.');renderCards();}}
  async function poll(){if(demo||polling||document.hidden)return;polling=true;try{let latest=await request('/api/status');const wasDanceActive=!!browserAudioDanceId&&['playing','paused'].includes(status.state),danceFinished=wasDanceActive&&!['playing','paused'].includes(latest.state);if(danceFinished)stopBrowserAudio();if(browserAudio&&browserAudioOnly&&!['playing','paused'].includes(latest.state))latest={...latest,state:'playing',routine_id:status.routine_id};if(!['playing','paused'].includes(latest.state)&&!browserAudio)musicOnlyPlayback=false;if(latest.state==='error'&&status.error!==latest.error)toast(latest.error||'Playback failed');status=latest;connection(true,status.robot_connected);}catch(e){connection(false,false);}finally{polling=false;}}
  async function action(path, confirm=false, successMessage=''){if(busy)return;busy=true;renderPlayer();renderCards();try{if(demo){status={...status,state:path.includes('/api/motions/')?'complete':path.endsWith('/pause')?'paused':path.endsWith('/stop')?'stopped':path.endsWith('/reset')?'idle':'playing',routine_id:selected?.id};}else status=await request(path,'POST','{}',{'Content-Type':'application/json',...(confirm?{'X-G1-Safety-Confirmed':'YES'}:{})});if(path.endsWith('/play'))musicOnlyPlayback=false;if(audioOutput==='browser'&&path.endsWith('/play')&&selected?.audio)playBrowserAudio(selected,true);if(browserAudio&&browserAudioDanceId){if(path.endsWith('/pause'))browserAudio.pause();else if(path.endsWith('/resume'))browserAudio.play().catch(()=>{});}connection(true,status.robot_connected);log('Playback: '+status.state);if(successMessage)toast(successMessage);}catch(e){toast(e.message);}finally{busy=false;renderPlayer();renderCards();}}
  async function connectRobot(){
    if(robotBusy||status.robot_connected)return;
    if(demo){toast('Robot connection is unavailable in the visual demo.');return;}
    robotBusy=true;connection(connected,false);
    try{status=await request('/api/robot/connect','POST','{}',{'Content-Type':'application/json'});connection(true,status.robot_connected);toast('Robot connected.');log('Robot connection established');}
    catch(e){connection(connected,false);toast('Robot connection failed: '+e.message);}
    finally{robotBusy=false;connection(connected,status.robot_connected);}
  }
  function deviceRow(device, mode){const row=document.createElement('div');row.className='bluetooth-device';const details=document.createElement('div');const name=document.createElement('strong');name.textContent=device.name;details.append(name);const button=document.createElement('button');button.type='button';button.className=device.connected?'subtle-button connected-device':'subtle-button';button.textContent=device.connected?'Connected':mode==='pair'?'Pair':'Connect';button.disabled=!!device.connected||busy;button.onclick=()=>bluetoothAction(mode==='pair'?'pair':'connect',device.address);row.append(details,button);return row;}
  function renderBluetooth(){const paired=$('bluetooth-paired-devices'),search=$('bluetooth-search-results');paired.replaceChildren();search.replaceChildren();if(!bluetoothDevices.length){const empty=document.createElement('p');empty.className='hint';empty.textContent='No paired Bluetooth audio devices.';paired.append(empty);}else bluetoothDevices.forEach(device=>paired.append(deviceRow(device,'connect')));const pairedAddresses=new Set(bluetoothDevices.map(device=>device.address));bluetoothSearch.filter(device=>!pairedAddresses.has(device.address)).forEach(device=>search.append(deviceRow(device,'pair')));}
  async function refreshBluetooth(){if(demo)return;try{const result=await request('/api/bluetooth/devices');bluetoothDevices=result.devices||[];renderBluetooth();}catch(e){toast('Bluetooth devices unavailable: '+e.message);}}
  async function bluetoothAction(actionName,address){if(busy)return;busy=true;renderBluetooth();try{const result=await request('/api/bluetooth/'+actionName+'/'+encodeURIComponent(address),'POST','{}',{'Content-Type':'application/json'},60000);bluetoothDevices=result.devices||[];bluetoothSearch=[];renderBluetooth();toast((result.device?.name||'Bluetooth audio')+' connected.');}catch(e){toast(e.message);}finally{busy=false;renderBluetooth();}}
  async function searchBluetooth(){if(busy)return;busy=true;$('bluetooth-search').disabled=true;try{const result=await request('/api/bluetooth/scan','POST','{}',{'Content-Type':'application/json'},20000);bluetoothSearch=result.devices||[];renderBluetooth();toast(bluetoothSearch.length?'Nearby devices found.':'No nearby Bluetooth devices found.');}catch(e){toast(e.message);}finally{busy=false;$('bluetooth-search').disabled=false;renderBluetooth();}}
  function setAudioOutput(value){audioOutput=value;$('music-output').value=value;}
  function openSettings(){$('address').value=address;setAudioOutput(audioOutput);$('settings-dialog').showModal();refreshBluetooth();}
  function openDanceConfirm(){pendingMotion=null;pendingUniStore=null;$('confirm-heading').textContent='Start this dance?';$('confirm-copy').textContent='Make sure the robot has space and the physical E-stop is ready.';$('confirm-action').textContent='Start dance';$('confirm-dialog').showModal();}
  function openMotionConfirm(motion){pendingUniStore=null;pendingMotion=motion;$('confirm-heading').textContent='Start '+motion.name+'?';$('confirm-copy').textContent='Make sure the robot has space and the physical E-stop is ready.';$('confirm-action').textContent='Start motion';$('confirm-dialog').showModal();}
  function openWalkRunConfirm(){pendingUniStore=null;pendingMotion='run-mode';$('confirm-heading').textContent='Enable Run Mode?';$('confirm-copy').textContent='The robot may move while entering Run Mode. Clear the area and keep the physical E-stop ready.';$('confirm-action').textContent='Enable Run Mode';$('confirm-dialog').showModal();}
  function openReadyModeConfirm(){pendingUniStore=null;pendingMotion='ready-mode';$('confirm-heading').textContent='Enter Ready Mode?';$('confirm-copy').textContent='The robot will enter Unitree Lock Stand and actively hold its standing pose. Clear the area and keep the physical E-stop ready.';$('confirm-action').textContent='Enter Ready Mode';$('confirm-dialog').showModal();}
  function openUniStoreConfirm(app){pendingMotion=null;pendingUniStore=app;$('confirm-heading').textContent='Start '+app.name+'?';$('confirm-copy').textContent='This starts the app’s full routine. No non-Damp stop command is available here. Clear the area and keep the physical E-stop ready.';$('confirm-action').textContent='Start UniStore dance';$('confirm-dialog').showModal();}
  async function startUniStore(app){if(busy)return;busy=true;renderCards();try{const result=await request('/api/unistore/'+encodeURIComponent(app.id)+'/play','POST','{}',{'Content-Type':'application/json','X-G1-Safety-Confirmed':'YES'});musicOnlyPlayback=false;if(result.playback)status=result.playback;if(audioOutput==='browser'&&app.audio)playBrowserAudio(app,true);connection(true,status.robot_connected);toast(app.name+' started.');}catch(e){toast(e.message);}finally{busy=false;renderPlayer();renderCards();}}
  function startSelected(item){selected=item;renderPlayer();if(item.kind==='unistore')openUniStoreConfirm(item);else if(item.kind==='preset')openMotionConfirm(item);else openDanceConfirm();}
  async function playMusic(item){if(!item.audio){toast('Add an MP3 in this action’s settings first.');return;}if(busy)return;busy=true;renderCards();try{if(audioOutput==='browser'){playBrowserAudio(item);status={...status,state:'playing',routine_id:item.id};}else{const path=item.kind==='routine'?'/api/routines/'+encodeURIComponent(item.id)+'/music':'/api/media/'+encodeURIComponent(item.kind)+'/'+encodeURIComponent(item.id)+'/music';status=demo?{...status,state:'playing',routine_id:item.id}:await request(path,'POST','{}',{'Content-Type':'application/json'});musicOnlyPlayback=true;}toast('Playing music for '+item.name+'.');}catch(e){toast(e.message);}finally{busy=false;renderPlayer();renderCards();}}
  const musicButton=document.createElement('button');musicButton.id='music';musicButton.type='button';musicButton.className='player-button music-button';musicButton.setAttribute('aria-label','Play attached music only');musicButton.title='Play attached music only';musicButton.disabled=true;musicButton.textContent='♫';$('toggle').after(musicButton);
  const outputField=document.createElement('label');outputField.className='field';outputField.textContent='Music output';const outputSelect=document.createElement('select');outputSelect.id='music-output';[['bluetooth','Local Bluetooth'],['usb','Local speakers'],['browser','Browser audio']].forEach(([value,label])=>{const option=document.createElement('option');option.value=value;option.textContent=label;outputSelect.append(option);});outputField.append(outputSelect);$('address').closest('label').after(outputField);
  outputSelect.onchange=async()=>{const output=outputSelect.value;try{if(!demo)await request('/api/settings/audio-output','PUT',JSON.stringify({audio_output:output}),{'Content-Type':'application/json'});setAudioOutput(output);toast('Music output set to '+outputSelect.selectedOptions[0].textContent+'.');}catch(error){setAudioOutput(audioOutput);toast('Could not change music output: '+error.message);}};
  const backupField=document.createElement('div');backupField.className='backup-actions';backupField.innerHTML='<div class="divider"></div><h3>App data backup</h3><p class="hint">Includes your routines, MP3s, videos, covers, favourites, and audio preference.</p><div><button class="subtle-button" id="export-app-data" type="button">Export app data</button><label class="subtle-button import-backup">Import app data<input id="import-app-data" type="file" accept=".zip,application/zip" hidden></label></div>';$('settings-form details').before(backupField);
  $('export-app-data').onclick=async()=>{try{await syncPreferences();const response=await fetch(address+'/api/app-data/export');if(!response.ok)throw Error('Export failed');const blob=await response.blob(),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='g1-dancer-backup.zip';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);toast('App data exported.');}catch(error){toast(error.message);}};
  $('import-app-data').onchange=event=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(file.size>500*1024*1024){toast('Choose a backup smaller than 500 MB.');return;}const xhr=new XMLHttpRequest();xhr.open('PUT',address+'/api/app-data/import');xhr.timeout=120000;xhr.setRequestHeader('Content-Type','application/zip');xhr.onload=async()=>{if(xhr.status>=200&&xhr.status<300){try{applyPreferences(JSON.parse(xhr.responseText).preferences);}catch{}await refresh();refreshUniStore();toast('App data restored.');}else{try{toast(JSON.parse(xhr.responseText).error);}catch{toast('Import failed.');}}};xhr.onerror=xhr.ontimeout=()=>toast('Import interrupted. Check the connection and try again.');xhr.send(file);};
  const removeAction=document.createElement('button');removeAction.id='remove-action';removeAction.type='button';removeAction.className='remove-action';removeAction.textContent='Remove from library';removeAction.title='Hide this action from this web app only';$('track-assets').after(removeAction);removeAction.onclick=async()=>{if(!editing||!confirm('Remove '+(editing.song_title||editing.name)+' from this library? It remains installed on the robot and its files are kept.'))return;busy=true;removeAction.disabled=true;try{await request('/api/library/'+encodeURIComponent(editing.kind)+'/'+encodeURIComponent(editing.id)+'/hide','DELETE');selected=null;$('track-dialog').close();await refresh();await refreshUniStore();toast('Removed from this library.');}catch(e){toast(e.message);}finally{busy=false;removeAction.disabled=false;renderPlayer();renderCards();}};
  $('menu').onclick=openSettings;$('settings-nav').onclick=openSettings;$('empty-settings').onclick=openSettings;document.querySelectorAll('[data-connect-robot]').forEach(button=>button.onclick=connectRobot);
  $('library-nav').onclick=()=>$('library').scrollIntoView({behavior:'smooth'});const selectFeatured=()=>{if(featured[featuredIndex]){selected=featured[featuredIndex];renderCards();renderPlayer();}};$('featured-hero').onclick=event=>{if(!event.target.closest('.featured-controls,.featured-actions'))selectFeatured();};$('featured-hero').onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectFeatured();}};
  $('featured-previous').onclick=()=>moveFeatured(-1);$('featured-next').onclick=()=>moveFeatured(1);let featuredTouchStart=null;$('featured-hero').addEventListener('touchstart',event=>{featuredTouchStart=event.changedTouches[0]?.clientX??null;},{passive:true});$('featured-hero').addEventListener('touchend',event=>{const end=event.changedTouches[0]?.clientX;if(featuredTouchStart!==null&&typeof end==='number'&&Math.abs(end-featuredTouchStart)>35)moveFeatured(end<featuredTouchStart?1:-1);featuredTouchStart=null;},{passive:true});
  $('featured-play').onclick=()=>{const item=featured[featuredIndex];if(item)startSelected(item);};$('featured-music').onclick=()=>{const item=featured[featuredIndex];if(item)playMusic(item);};
  $('refresh').onclick=()=>{refresh();refreshUniStore();};$('search').oninput=renderCards;
  document.querySelectorAll('[data-dance-filter]').forEach(b=>b.onclick=()=>{danceFilter=b.dataset.danceFilter;document.querySelectorAll('[data-dance-filter]').forEach(c=>c.classList.toggle('selected',c===b));renderCards();});
  document.querySelectorAll('[data-motion-filter]').forEach(b=>b.onclick=()=>{motionFilter=b.dataset.motionFilter;document.querySelectorAll('[data-motion-filter]').forEach(c=>c.classList.toggle('selected',c===b));renderCards();});
  document.querySelectorAll('[data-utility-filter]').forEach(b=>b.onclick=()=>{utilityFilter=b.dataset.utilityFilter;document.querySelectorAll('[data-utility-filter]').forEach(c=>c.classList.toggle('selected',c===b));renderCards();});
  document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
  document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();}));
  $('settings-form').onsubmit=async e=>{e.preventDefault();try{const u=new URL($('address').value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw Error('Enter an HTTP address');if(!native&&u.origin!==location.origin){location.assign(u.origin);return;}address=u.origin;localStorage.setItem('g1.address',address);const output=$('music-output').value;if(!demo)await request('/api/settings/audio-output','PUT',JSON.stringify({audio_output:output}),{'Content-Type':'application/json'});setAudioOutput(output);$('settings-dialog').close();refresh();}catch(e){toast(e.message);}};
  $('bluetooth-search').onclick=searchBluetooth;
  $('toggle').onclick=()=>{if(status.state==='playing')action('/api/pause');else if(status.state==='paused')action('/api/resume');else if(selected)startSelected(selected);};
  $('music').onclick=()=>{if(selected)playMusic(selected);};
  $('stop').onclick=()=>{if(browserAudio){const onlyMusic=browserAudioOnly;stopBrowserAudio();if(onlyMusic){status={...status,state:'stopped'};renderPlayer();renderCards();toast('Browser music stopped.');return;}}action('/api/stop',false,'Motion stopped.');};$('robot-ready-mode').onclick=openReadyModeConfirm;$('robot-walk-run').onclick=openWalkRunConfirm;$('robot-damped-mode').onclick=()=>action('/api/robot/damped-mode',false,'Damped Mode active.');$('confirm-action').onclick=()=>{const motion=pendingMotion,app=pendingUniStore;pendingMotion=null;pendingUniStore=null;$('confirm-dialog').close();if(app)startUniStore(app);else if(motion==='ready-mode')action('/api/robot/ready-mode',true,'Ready Mode enabled: Lock Stand active.');else if(motion==='run-mode')action('/api/robot/run-mode',true,'Run Mode enabled.');else if(motion)action('/api/motions/'+encodeURIComponent(motion.id)+'/play',true,motion.name+(demo?' simulated.':' started.'));else action('/api/routines/'+encodeURIComponent(selected.id)+'/play',true);};
  function openTrackSettings(item){editing=item;$('track-heading').textContent=item.song_title||item.name;$('track-heading').title='Click to edit this action name';$('track-title').value=item.song_title||item.name;$('detail-art').src=art(item);$('attached-audio').textContent=item.audio?'Attached MP3: '+(item.audio_filename||item.name+'.mp3')+' — it will remain linked until replaced.':'No MP3 is attached yet.';$('track-name-settings').hidden=true;$('cover-settings').hidden=item.kind!=='routine';$('mimic-name-hint').hidden=item.kind!=='mimic';$('track-dialog').showModal();}
  $('edit').onclick=()=>{if(selected)openTrackSettings(selected);};
  $('track-heading').onclick=()=>{if(!editing)return;$('track-name-settings').hidden=false;$('track-title').focus();$('track-title').select();};$('track-heading').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('track-heading').click();}};$('track-heading').tabIndex=0;$('track-heading').setAttribute('role','button');
  $('save-title').onclick=async()=>{const title=$('track-title').value.trim();if(!editing||!title){toast('Enter a display name.');return;}busy=true;$('save-title').disabled=true;try{const path=(editing.kind==='routine'||editing.kind==='mimic')?'/api/routines/'+encodeURIComponent(editing.id)+'/title':'/api/media/'+encodeURIComponent(editing.kind)+'/'+encodeURIComponent(editing.id)+'/title';await request(path,'PUT',JSON.stringify({title}),{'Content-Type':'application/json'});$('track-dialog').close();await refresh();refreshUniStore();toast('Display name updated.');}catch(e){toast(e.message);}finally{busy=false;$('save-title').disabled=false;renderPlayer();}};
  function upload(file,kind){if(!file||!editing)return;const id=editing.id;if(demo){toast('Demo mode: uploads are disabled. Connect to a development PC to save files.');return;}if(kind==='audio'&&!/\.mp3$/i.test(file.name)){toast('Choose an MP3 file.');return;}if(kind==='video'&&!/\.(mp4|webm)$/i.test(file.name)){toast('Choose an MP4 or WebM video.');return;}const max=kind==='artwork'?5:100;if(file.size>max*1024*1024){toast('Choose a file smaller than '+max+' MB.');return;}
    const base=editing.kind==='routine'?'/api/routines/'+encodeURIComponent(id):'/api/media/'+encodeURIComponent(editing.kind)+'/'+encodeURIComponent(id);busy=true;renderPlayer();$('upload-progress').hidden=false;const xhr=new XMLHttpRequest();xhr.open('PUT',address+base+'/'+kind);xhr.timeout=120000;if(kind==='audio')xhr.setRequestHeader('X-Original-Filename',encodeURIComponent(file.name));xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)$('upload-progress').value=100*e.loaded/e.total;};
    const done=()=>{busy=false;$('upload-progress').hidden=true;renderPlayer();};xhr.onload=async()=>{done();if(xhr.status>=200&&xhr.status<300){toast(kind==='audio'?'Song linked.':kind==='video'?'Hover video linked.':'Cover updated on all devices.');$('track-dialog').close();await refresh();refreshUniStore();}else{try{toast(JSON.parse(xhr.responseText).error);}catch{toast('Upload failed.');}}};xhr.onerror=xhr.ontimeout=()=>{done();toast('Upload interrupted. Check the connection and try again.');};xhr.send(file);
  }
  $('song-file').onchange=e=>{upload(e.target.files[0],'audio');e.target.value='';};$('cover-file').onchange=e=>{upload(e.target.files[0],'artwork');e.target.value='';};$('video-file').onchange=e=>{upload(e.target.files[0],'video');e.target.value='';};
  // Native bundle defaults to the hotspot; browsers use their own server origin.
  if(!native)address=location.origin;
  refresh();refreshUniStore();setInterval(poll,2000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll();});
})();
